### ISSUE TITLE
Capacitor 3

### ISSUE THREAD

**Issue by AE1NS** [aparajita/capacitor-secure-storage#1]
Will you update this plugin to support Capacitor 3?

**Comment by aparajita** [comment]
I plan to upgrade the plugins to Capacitor 3 when I convert my apps to Capacitor 3. I can't say for sure when that will happen.

**Comment by oberbayer** [comment]
+1 for this request. Thank you very much for your work on this plugin. But it would be so cool if it would build for min. iOS 12+

**Comment by aparajita** [comment]
Finally got approval to upgrade the plugins to Capacitor 3. Work is going on now, the new version should be ready in the next few weeks and will be published to @capacitor-community.

**Comment by schnouz** [comment]
Thanks a lot :)

**Comment by aparajita** [comment]
Thanks for your patience, it will definitely be coming this week or early next week.

**Comment by schnouz** [comment]
Thanks a lot for your works :) 
By the way on Android, does it throw an error for version inferior to Android 4.0  ( KeyStore introduce a 4.0 ) ?

**Comment by aparajita** [comment]
Android 5.0 (API 21) is the minimum version supported by Capacitor 2. The minimum version for Capacitor 4 is 5.1 (API 22).

**Comment by schnouz** [comment]
Last question :) Is the system keychain on IOS is auto sync to the Cloud ? Regards

**Comment by aparajita** [comment]
> Last question :) Is the system keychain on IOS is auto sync to the iCloud ? Regards

Currently no, I will have to add that as an option.

**Comment by schnouz** [comment]
thanks a lot :) Do you have any estimation date for the release of the Capacitor v4 compatibility update ?

**Comment by aparajita** [comment]
This coming week.

**Comment by schnouz** [comment]
Hey very sorry to ask again, but do you have a new estimation date ? I will release an app that needs this feature so that's why. Thanks again for all the great works on your plugins, very appreciated !

**Comment by aparajita** [comment]
Sorry, I was finishing up my splash screen plugin and Android dragged me to hell and back. That will be done tomorrow, then I can work on this plugin which should be straightforward. So I do anticipate a release this week.

**Comment by schnouz** [comment]
No worries thanks a lot for everything !

**Comment by aparajita** [comment]
You'll want to take a look at the splash screen plugin when it's done. It will be worth the wait. 😁

**Comment by schnouz** [comment]
Ahah I'm actually using this one `@capacitor/splash-screen` but will definitely check on it ! Thanks

**Comment by schnouz** [comment]
Hi there :) Just to know if the update will be ready this week ?

**Comment by AE1NS** [comment]
Closed due to https://github.com/aparajita/capacitor-secure-storage/issues/2

**Comment by aparajita** [comment]
Hey gang, v2.0.0 has just been released with full support for iCloud Keychain. 🔥

Be sure to read the docs and the [API](https://github.com/aparajita/capacitor-secure-storage/blob/main/src/definitions.ts), there are some changes.
