### ISSUE TITLE
bug: android app does not start if secure storage is accessed

### ISSUE THREAD

**Issue by chris-si** [aparajita/capacitor-secure-storage#11]
## Bug report

Hi, I just ran into a problem while trying to add the android platform to my project. The `setKeyPrefix` method seems to not work correctly. On iOS everything is working as expected.

Edit:
It's not only `setKeyPrefix` method that is not working. If I don't use the `setKeyPrefix` method the access (write and read) via `set` and `get` also results in the case that the app doesn't load correctly and no error is thrown.

### Capacitor version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 6.1.0
  @capacitor/core: 6.1.0
  @capacitor/android: 6.1.0
  @capacitor/ios: 6.1.0

Installed Dependencies:

  @capacitor/cli: 6.1.0
  @capacitor/android: 6.1.0
  @capacitor/core: 6.1.0
  @capacitor/ios: 6.1.0

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

```
"@aparajita/capacitor-secure-storage": "^6.0.0"
```

### Platform(s)

- android

### Current behavior

When `setKeyPrefix`, `set` or `get` is called, the app hangs and is not executed properly (white screen). No error is thrown.

### Expected behavior

The methods should be usable without problems as possible on the web and iOS

### Code reproduction

1. Clone [this repo](https://github.com/chris-si/capacitor-android-test/tree/secure-storage-plugin-setKeyPrefix) (branch `secure-storage-plugin-setKeyPrefix`)
2. Run `npm install`
3. Run `ionic cap build android`
4. Run the app on an android device/simulator (the logs show where the app hangs)

### Other technical details

Tests were conducted on android simulators with the API levels 30,33 and 35. All three show the same behavior.

npm: 10.6.0
node: v20.12.2

**Comment by aparajita** [comment]
You might want to spend some time understanding vite's build process and how to configure the legacy plugin. The problem is not in this plugin, it's that the vite build is misconfigured and you are using top level await. The app hung when calling this plugin because that was the first await after the top level await.

**Comment by chris-si** [comment]
Thanks for your answer. I just compiled to `esnext` without the `legacy` vite plugin but the behavior is still the same.

A new reproduction on branch `main` also shows that the top-level await seems to work fine. Other awaits are called without any problems before the secure storage is accessed. The app again only hangs when trying to interact with the secure storage plugin on android.
Web and iOS are also working fine again on this branch.

**Comment by chris-si** [comment]
Just as a test I added [another secure storage plugin](https://www.npmjs.com/package/capacitor-secure-storage-plugin) just for Android to the test project on the branch `androidSecStore2`. This (from my quick look at the code) also somehow accesses the Android keystore and and SharedPreferences. In the same context of my test project, the android app doesn't hang when the secure storage is accessed with this plugin.

**Comment by aparajita** [comment]
If in fact the plugin was as broken as you suggest, I would be getting lots of complaints, but this is the only such report I have received.

If you run on Android using `--live-reload`, which does not compile with esbuild, everything works fine, so there seems to be an issue with how vite/esbuild is compiling the code in the presence of top level await.

Top level await is really unnecessary in your code. You can either replace `await` with `void`, or use `.then()` instead.

Unfortunately I don't have any more time to spend on this, so if you are determined to use top level await, I will document that this plugin cannot be used with top level await, and I suggest using another plugin.
