### ISSUE TITLE
Capacitor 4

### ISSUE THREAD

**Issue by AE1NS** [aparajita/capacitor-secure-storage#2]
Will you update this plugin to support Capacitor 4?

- Update podfile to version ios 13
- Update build.gradle like here [Cap 4 update of another plugin](https://github.com/NePheus/capacitor-android-shortcuts/commit/099d865aa572d7fa7bfc90af3885c01b259d3e5e#diff-197b190e4a3512994d2cebed8aff5479ff88e136b8cc7a4b148ec9c3945bd65a)
- Question: Does standard-version really needs to be a peerDependencies inside the package.json?
- Refactor your native decorator

**Comment by AE1NS** [comment]
Hey @aparajita,

do you have an updates/progress regarding this? :)
I just saw, that you finished your splash screen plugin.
Thanks for your work!

**Comment by aparajita** [comment]
Now that I finished splash screen I will start working on this one today.

**Comment by aparajita** [comment]
Just released with iCloud Keychain support!
