### ISSUE TITLE
feat: Some usage examples or demo for Angular

### ISSUE THREAD

**Issue by rgbaman** [aparajita/capacitor-secure-storage#3]
**Is your feature request related to a problem? Please describe.**

This plugin looks promising but I'm struggling to compare and implement on Angular when the demo is written for Vue.

Are you able to provide some usage examples for Angular?

**Describe the solution you'd like**

Either a demo (like the Vue version you have done) or some usage examples for Angular.

**Describe alternatives you've considered**

Following the Vue demo... but I don't work with Vue and find it difficult to translate in to Angular.

**Comment by aparajita** [comment]
Sorry, I don't work with Angular, can't help you there. The plugin API is the same in any framework.

**Comment by aparajita** [comment]
```ts
import { SecureStorage } from '@aparajita/capacitor-secure-storage'

await SecureStorage.set('foo', 'bar')
const value = await SecureStorage.get('foo')
// value === 'bar'
await SecureStorage.remove('foo')
```
