### ISSUE TITLE
Capacitor 5

### ISSUE THREAD

**Issue by NePheus** [aparajita/capacitor-secure-storage#6]
Are you going to update the plugin to support Capacitor 5? Capacitor 5 should be released soon.

https://capacitorjs.com/docs/next/updating/plugins/5-0

**Comment by aparajita** [comment]
Yes, when it reaches RC.

**Comment by aub** [comment]
@aparajita it's released now, would be lovely to have it supported here. Thanks

**Comment by avioli** [comment]
@aparajita I'm working on a PR for this as well as the demo repo of the plugin.

**Comment by aparajita** [comment]
I will be updating all of my plugins next week, you don't have to.

**Comment by aparajita** [comment]
Just updated to Capacitor 5.
